@startuml
hide footbox
autoactivate on

利用者 -> 車止め : 車を止める
車止め ->タイマー: 車止めをあげる
deactivate 車止め
タイマー -> 料金メーター:料金表示 
料金メーター --> タイマー:表示完了
deactivate 料金メーター
loop 経過時間に応じて
    タイマー -> 料金メーター: 料金増加・更新指示
    料金メーター -->タイマー:表示更新終了
end
deactivate タイマー
利用者 ->料金ボックス:料金精算
deactivate タイマー
料金ボックス -> 車止め:車止め解除
車止め --> 料金ボックス: 解除完了
料金ボックス -> 売り上げ管理システム : 売り上げ報告
売り上げ管理システム --> 料金ボックス :登録完了
料金ボックス --> 利用者 :精算完了
deactivate 車止め 
@enduml
